import jsPDF from "jspdf";
import type {
  AssessmentData,
  ReportSnapshot,
  SubjectStrategiesStored,
} from "@/lib/student-store";
import {
  buildConversationBlocks,
  renderConversationSection,
  type ConversationPdfLabels,
} from "@/lib/progress-report-pdf";
import { getTeacherPdfLines, type TeacherProfilePdf } from "@/lib/teacher-profile";
import { triggerBrowserPdfDownload } from "@/lib/pdf-download";

export interface DownloadFinalReportPdfOptions {
  studentName: string;
  assessmentData: AssessmentData;
  snapshot: ReportSnapshot;
  /** Idioma de la UI (es/en) para etiquetas del PDF */
  uiLanguage: "es" | "en";
  teacherProfile?: TeacherProfilePdf;
}

const SUBJECT_LABELS: {
  key: keyof SubjectStrategiesStored;
  es: string;
  en: string;
  kaqchikel: string;
}[] = [
  { key: "numeracy", es: "Área numérica / Matemáticas", en: "Numeracy / Mathematics", kaqchikel: "Ajilab'al" },
  { key: "language", es: "Lenguaje y lectoescritura", en: "Language and literacy", kaqchikel: "Tz'ib'axik" },
  { key: "foreignLanguage", es: "Nuevo idioma", en: "New language", kaqchikel: "Ch'ab'al k'ak'a'" },
  { key: "arts", es: "Artes", en: "Arts", kaqchikel: "B'itz'ib'" },
  { key: "ict", es: "TIC", en: "ICT", kaqchikel: "TIC" },
  { key: "other", es: "Otros apoyos", en: "Other supports", kaqchikel: "Juley chik" },
];

/** Genera y descarga el PDF de forma síncrona (evita bloqueo del navegador tras await). */
export function downloadFinalReportPdf(options: DownloadFinalReportPdfOptions): void {
  const { studentName, assessmentData, snapshot, uiLanguage, teacherProfile } = options;
  const isEs = uiLanguage === "es";
  const reportLang = snapshot.reportLanguage;

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageHeight = 297;
  const marginTop = 22;
  const marginLeft = 20;
  const marginRight = 20;
  const maxWidth = 210 - marginLeft - marginRight;
  const lineHeight = 5.5;
  const lineHeightTitle = 7;
  const bottomMargin = 25;
  const maxY = pageHeight - bottomMargin;
  let cursorY = marginTop;

  const maybeNewPage = (needed: number) => {
    if (cursorY + needed > maxY) {
      doc.addPage();
      cursorY = marginTop;
    }
  };

  const addTitle = (text: string) => {
    maybeNewPage(lineHeightTitle * 2);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(15, 76, 129);
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((l: string) => {
      doc.text(l, marginLeft, cursorY);
      cursorY += lineHeight;
    });
    doc.setTextColor(0, 0, 0);
    cursorY += 3;
  };

  const addSubtitle = (text: string) => {
    maybeNewPage(lineHeightTitle);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(text, marginLeft, cursorY);
    cursorY += lineHeight + 2;
  };

  const addSectionTitle = (text: string) => {
    maybeNewPage(lineHeightTitle + 2);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(15, 76, 129);
    doc.text(text, marginLeft, cursorY);
    doc.setTextColor(0, 0, 0);
    cursorY += lineHeight + 2;
  };

  const addBulletList = (items: string[]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const bullet = "  \u2022 ";
    items.forEach((item) => {
      const wrapped = doc.splitTextToSize(bullet + String(item).trim(), maxWidth - 8);
      wrapped.forEach((l: string) => {
        maybeNewPage(lineHeight);
        doc.text(l, marginLeft, cursorY);
        cursorY += lineHeight;
      });
    });
    cursorY += 2;
  };

  const title =
    reportLang === "kaqchikel"
      ? "Rutz'ib'axik ruk'uxik (informe final)"
      : reportLang === "en"
        ? "Final integrated follow-up report"
        : "Informe final de seguimiento integrado";

  addTitle(title);
  addSubtitle(
    `${isEs ? "Estudiante" : "Student"}: ${studentName.trim() || (isEs ? "Sin nombre" : "Unnamed")}`
  );
  for (const line of getTeacherPdfLines(teacherProfile, isEs)) {
    addSubtitle(line);
  }
  addSubtitle(
    `${isEs ? "Generado por EDUGUIA" : "Generated by EDUGUIA"} · ${new Date().toLocaleDateString(isEs ? "es-GT" : "en-US")}`
  );
  cursorY += 2;

  snapshot.report.forEach((section) => {
    addSectionTitle(section.title);
    addBulletList(section.content);
  });

  const subjectSectionTitle =
    reportLang === "kaqchikel"
      ? "Tz'ukul pa k'ojlib'al"
      : reportLang === "en"
        ? "Subject-specific strategies"
        : "Estrategias por materia";

  const ss = snapshot.subjectStrategies ?? {
    numeracy: [],
    language: [],
    foreignLanguage: [],
    arts: [],
    ict: [],
    other: [],
  };
  const hasSubjects = SUBJECT_LABELS.some(({ key }) => ss[key]?.length);
  if (hasSubjects) {
    addSectionTitle(subjectSectionTitle);
    SUBJECT_LABELS.forEach(({ key, es, en, kaqchikel }) => {
      const items = ss[key];
      if (!items?.length) return;
      const label = reportLang === "kaqchikel" ? kaqchikel : reportLang === "en" ? en : es;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      maybeNewPage(lineHeight);
      doc.text(`${label}:`, marginLeft, cursorY);
      cursorY += lineHeight;
      addBulletList(items);
    });
  }

  const kaqTitle =
    reportLang === "kaqchikel"
      ? "Rutz'ib'axik richin ri ajay (Kaqchikel)"
      : isEs
        ? "Resumen para la familia en Kaqchikel"
        : "Family summary (Kaqchikel)";

  addSectionTitle(kaqTitle);
  const kaqLines =
    snapshot.familySummaryKaqchikel?.length >= 3
      ? snapshot.familySummaryKaqchikel
      : [
          "Tz'etel ala' pa ruq'a' ruk'u'x, xa jun chi q'ij.",
          "Taqa' to'ob'äl pa jay ruma ri ala'.",
          "Titzijonïk pa tinamit chuqa' pa jay richin ri ala' nuk'äm.",
        ];
  addBulletList(kaqLines);

  const pdfLabels: ConversationPdfLabels = {
    sectionTitle: isEs ? "Conversación con EduGuIA (historial completo)" : "Conversation with EduGuIA (full history)",
    assessmentPhase: isEs ? "Evaluación adaptativa" : "Adaptive assessment",
    followUpPhase: isEs ? "Seguimiento posterior" : "Follow-up",
    teacher: isEs ? "Docente:" : "Teacher:",
    ai: "EduGuIA:",
    timeline: "",
    typeAssessment: "",
    typeObservation: "",
    typeMilestone: "",
    typeIntervention: "",
    noConversation: isEs ? "Sin conversación registrada." : "No conversation recorded.",
    noTimeline: "",
  };

  cursorY += 4;
  const pdfCtx = {
    doc,
    marginLeft,
    maxWidth,
    lineHeight,
    maxY,
    marginTop,
    getY: () => cursorY,
    setY: (y: number) => {
      cursorY = y;
    },
    maybeNewPage,
  };

  const conversationBlocks = buildConversationBlocks(assessmentData);
  renderConversationSection(pdfCtx, conversationBlocks, pdfLabels);
  cursorY = pdfCtx.getY() + 6;

  maybeNewPage(15);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  const footer = isEs
    ? "Informe generado por EDUGUIA a partir de la evaluación y el seguimiento con IA. No constituye diagnóstico clínico."
    : "Report generated by EDUGUIA from assessment and AI follow-up. Not a clinical diagnosis.";
  doc.splitTextToSize(footer, maxWidth).forEach((l: string) => {
    doc.text(l, marginLeft, cursorY);
    cursorY += lineHeight;
  });

  const safeName = studentName.replace(/\s+/g, "_").slice(0, 30) || "estudiante";
  triggerBrowserPdfDownload(doc, `Informe_Final_${safeName}.pdf`);
}
